import { ProtocolConversionError } from '../errors.js';
import type { EventTable, IntBounds, ProtocolDefinition, TypeInfo } from './definition.js';

/**
 * Convert one of Blizzard's `protocolNNNNN.py` files into a ProtocolDefinition.
 *
 * The Python file is generated by Blizzard's tooling and consists of literals
 * only — a list of tuples for `typeinfos`, dicts for the event tables and a
 * handful of `name = number` assignments. So rather than pattern-match lines
 * with regular expressions (the 2018 approach, which broke on any formatting
 * change), the relevant blocks are parsed with a small recursive-descent parser
 * for that literal subset. Anything outside the subset is an error naming the
 * offending text, never a silently empty protocol.
 *
 * Runs at build time to produce the bundled definitions, and at runtime as the
 * fallback for a build newer than the bundle.
 */
export function convertPythonProtocol(source: string, build: number): ProtocolDefinition {
  const typeinfoLines = blockLines(source, /^typeinfos\s*=\s*\[\s*$/m, /^\]/m, 'typeinfos');
  const typeinfos = typeinfoLines.map((line, i) => toTypeInfo(parseLiteral(stripComment(line)), i));

  const readTable = (name: string): EventTable => {
    const lines = blockLines(source, new RegExp(`^${name}\\s*=\\s*\\{\\s*$`, 'm'), /^\}/m, name);
    const table: Record<number, readonly [number, string]> = {};
    for (const raw of lines) {
      const line = stripComment(raw);
      const colon = line.indexOf(':');
      if (colon < 0) throw new ProtocolConversionError(`${name}: expected "id: (typeid, 'name')", got ${JSON.stringify(line)}`);
      const id = Number(line.slice(0, colon).trim());
      const value = parseLiteral(line.slice(colon + 1));
      if (!Number.isInteger(id) || !Array.isArray(value) || value.length !== 2 || typeof value[0] !== 'number' || typeof value[1] !== 'string') {
        throw new ProtocolConversionError(`${name}: malformed entry ${JSON.stringify(line)}`);
      }
      table[id] = [value[0], value[1]];
    }
    return table;
  };

  const readTypeid = (name: string): number => {
    const m = new RegExp(`^${name}\\s*=\\s*(\\d+)\\s*$`, 'm').exec(source);
    if (m === null) throw new ProtocolConversionError(`missing "${name} = N"`);
    return Number(m[1]);
  };

  const def: ProtocolDefinition = {
    build,
    typeinfos,
    gameEventTypes: readTable('game_event_types'),
    messageEventTypes: readTable('message_event_types'),
    trackerEventTypes: readTable('tracker_event_types'),
    gameEventIdTypeid: readTypeid('game_eventid_typeid'),
    messageEventIdTypeid: readTypeid('message_eventid_typeid'),
    trackerEventIdTypeid: readTypeid('tracker_eventid_typeid'),
    svaruint32Typeid: readTypeid('svaruint32_typeid'),
    replayUserIdTypeid: readTypeid('replay_userid_typeid'),
    headerTypeid: readTypeid('replay_header_typeid'),
    detailsTypeid: readTypeid('game_details_typeid'),
    initDataTypeid: readTypeid('replay_initdata_typeid'),
  };
  validate(def);
  return def;
}

/** Lines strictly between a start line and the first end line after it. */
function blockLines(source: string, start: RegExp, end: RegExp, what: string): string[] {
  const s = start.exec(source);
  if (s === null) throw new ProtocolConversionError(`missing "${what}" block`);
  const from = s.index + s[0].length;
  const rest = source.slice(from);
  const e = end.exec(rest);
  if (e === null) throw new ProtocolConversionError(`unterminated "${what}" block`);
  return rest
    .slice(0, e.index)
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
}

/** Drop a trailing `#...` comment and trailing comma. */
function stripComment(line: string): string {
  let out = line;
  // A '#' inside a quoted string would break this, but protocol names never contain one.
  const hash = out.indexOf('#');
  if (hash >= 0) out = out.slice(0, hash);
  out = out.trim();
  if (out.endsWith(',')) out = out.slice(0, -1);
  return out.trim();
}

type Literal = number | string | null | Literal[] | { [key: string]: Literal };

/** Recursive-descent parser for the Python literal subset the protocol files use. */
function parseLiteral(text: string): Literal {
  let i = 0;
  const peek = (): string => text[i] ?? '';
  const ws = (): void => {
    while (i < text.length && /\s/.test(text[i]!)) i++;
  };
  const expect = (ch: string): void => {
    ws();
    if (text[i] !== ch) throw new ProtocolConversionError(`expected "${ch}" at ${i} in ${JSON.stringify(text)}`);
    i++;
  };
  const value = (): Literal => {
    ws();
    const c = peek();
    if (c === '(' || c === '[') {
      const close = c === '(' ? ')' : ']';
      i++;
      const items: Literal[] = [];
      ws();
      while (peek() !== close) {
        items.push(value());
        ws();
        if (peek() === ',') {
          i++;
          ws();
        }
      }
      i++;
      return items;
    }
    if (c === '{') {
      i++;
      const obj: { [key: string]: Literal } = {};
      ws();
      while (peek() !== '}') {
        const key = value();
        expect(':');
        obj[String(key)] = value();
        ws();
        if (peek() === ',') {
          i++;
          ws();
        }
      }
      i++;
      return obj;
    }
    if (c === "'" || c === '"') {
      i++;
      let s = '';
      while (i < text.length && text[i] !== c) s += text[i++];
      if (text[i] !== c) throw new ProtocolConversionError(`unterminated string in ${JSON.stringify(text)}`);
      i++;
      return s;
    }
    if (text.startsWith('None', i)) {
      i += 4;
      return null;
    }
    const m = /^-?\d+/.exec(text.slice(i));
    if (m === null) throw new ProtocolConversionError(`unexpected "${c}" at ${i} in ${JSON.stringify(text)}`);
    i += m[0].length;
    return Number(m[0]);
  };
  const result = value();
  ws();
  if (i !== text.length) throw new ProtocolConversionError(`trailing text in ${JSON.stringify(text)}`);
  return result;
}

function bounds(v: Literal, where: string): IntBounds {
  if (!Array.isArray(v) || v.length !== 2 || typeof v[0] !== 'number' || typeof v[1] !== 'number') {
    throw new ProtocolConversionError(`${where}: expected (min, bits), got ${JSON.stringify(v)}`);
  }
  return [v[0], v[1]];
}

/** `('_kind', [args])` → TypeInfo */
function toTypeInfo(lit: Literal, index: number): TypeInfo {
  const where = `typeinfo #${index}`;
  if (!Array.isArray(lit) || lit.length !== 2 || typeof lit[0] !== 'string' || !Array.isArray(lit[1])) {
    throw new ProtocolConversionError(`${where}: expected ('_kind', [args]), got ${JSON.stringify(lit)}`);
  }
  const [kind, args] = lit;
  switch (kind) {
    case '_int':
      return { k: 'int', bounds: bounds(args[0]!, where) };
    case '_blob':
      return { k: 'blob', bounds: bounds(args[0]!, where) };
    case '_bitarray':
      return { k: 'bitarray', bounds: bounds(args[0]!, where) };
    case '_bool':
      return { k: 'bool' };
    case '_fourcc':
      return { k: 'fourcc' };
    case '_null':
      return { k: 'null' };
    case '_real32':
      return { k: 'real32' };
    case '_real64':
      return { k: 'real64' };
    case '_array':
      if (typeof args[1] !== 'number') throw new ProtocolConversionError(`${where}: array needs a typeid`);
      return { k: 'array', bounds: bounds(args[0]!, where), typeid: args[1] };
    case '_optional':
      if (typeof args[0] !== 'number') throw new ProtocolConversionError(`${where}: optional needs a typeid`);
      return { k: 'optional', typeid: args[0] };
    case '_choice': {
      const dict = args[1];
      if (dict === null || typeof dict !== 'object' || Array.isArray(dict)) {
        throw new ProtocolConversionError(`${where}: choice needs a dict`);
      }
      const choices: Record<number, readonly [string, number]> = {};
      for (const [tag, v] of Object.entries(dict)) {
        if (!Array.isArray(v) || typeof v[0] !== 'string' || typeof v[1] !== 'number') {
          throw new ProtocolConversionError(`${where}: malformed choice ${tag}`);
        }
        choices[Number(tag)] = [v[0], v[1]];
      }
      return { k: 'choice', bounds: bounds(args[0]!, where), choices };
    }
    case '_struct': {
      const list = args[0];
      if (!Array.isArray(list)) throw new ProtocolConversionError(`${where}: struct needs a field list`);
      const fields = list.map((f): readonly [string, number, number] => {
        if (!Array.isArray(f) || typeof f[0] !== 'string' || typeof f[1] !== 'number' || typeof f[2] !== 'number') {
          throw new ProtocolConversionError(`${where}: malformed struct field ${JSON.stringify(f)}`);
        }
        return [f[0], f[1], f[2]];
      });
      return { k: 'struct', fields };
    }
    default:
      throw new ProtocolConversionError(`${where}: unknown type kind ${JSON.stringify(kind)}`);
  }
}

/** Every typeid referenced anywhere must exist. */
function validate(def: ProtocolDefinition): void {
  const n = def.typeinfos.length;
  const check = (id: number, where: string): void => {
    if (!Number.isInteger(id) || id < 0 || id >= n) {
      throw new ProtocolConversionError(`${where} references typeid ${id}, but there are ${n} types`);
    }
  };
  def.typeinfos.forEach((t, i) => {
    if (t.k === 'array' || t.k === 'optional') check(t.typeid, `typeinfo #${i}`);
    if (t.k === 'choice') for (const [, id] of Object.values(t.choices)) check(id, `typeinfo #${i}`);
    if (t.k === 'struct') for (const [, id] of t.fields) check(id, `typeinfo #${i}`);
  });
  for (const name of ['gameEventTypes', 'messageEventTypes', 'trackerEventTypes'] as const) {
    for (const [id, [typeid]] of Object.entries(def[name])) check(typeid, `${name}[${id}]`);
  }
  for (const name of ['gameEventIdTypeid', 'messageEventIdTypeid', 'trackerEventIdTypeid', 'svaruint32Typeid', 'replayUserIdTypeid', 'headerTypeid', 'detailsTypeid', 'initDataTypeid'] as const) {
    check(def[name], name);
  }
}
