/** Regenerate src/data/builds.ts from the heroes-data repository tree: `pnpm run generate.hero-data-builds`. */
import { writeFileSync } from 'node:fs';
import { format, resolveConfig } from 'prettier';
import { parseBuildDirectories } from '../src/providers.js';

const API = 'https://api.github.com/repos/HeroesToolChest/heroes-data/git/trees/master';
const headers: Record<string, string> = { accept: 'application/vnd.github+json' };
if (process.env['GITHUB_TOKEN']) headers['authorization'] = `Bearer ${process.env['GITHUB_TOKEN']}`;

const root = (await (await fetch(API, { headers })).json()) as {
  tree: { path: string; sha: string }[];
};
const dir = root.tree.find((t) => t.path === 'heroesdata')!;
const sub = (await (
  await fetch(`${API.replace(/master$/, '')}${dir.sha}`, { headers })
).json()) as { tree: { path: string }[] };
const builds = parseBuildDirectories(sub.tree.map((t) => t.path));

const out = new URL('../src/data/builds.ts', import.meta.url).pathname;
const body = builds
  .map(
    (b) =>
      `  { build: ${b.build}, version: '${b.version}', ptr: ${b.ptr}, directory: '${b.directory}' },`,
  )
  .join('\n');
const source = `// Generated by tools/generate-builds.mts from HeroesToolChest/heroes-data. Do not edit.
import type { HeroDataBuild } from '../types.js';

/** Every build directory published in heroes-data, ascending by build number. */
export const KNOWN_BUILDS: readonly HeroDataBuild[] = [
${body}
];
`;
writeFileSync(out, await format(source, { ...((await resolveConfig(out)) ?? {}), filepath: out }));
console.log(`${builds.length} builds -> ${out}`);
