/**
 * Regenerate the bundled protocol definitions from Blizzard/heroprotocol.
 *
 *   pnpm protocols:generate                # from GitHub (needs network)
 *   pnpm protocols:generate --from <dir>   # from a directory of protocolNNNNN.py
 *
 * Blizzard publishes one file per build, but most builds share a definition
 * byte-for-byte: 390 files are 36 distinct protocols. Files are deduplicated by
 * their git blob SHA, one representative (the lowest build) is converted per
 * distinct definition, and `build-index` records which representative every
 * published build maps to. The SHA is kept per representative so a freshly
 * fetched tree listing can classify a NEW build as "same protocol as X" at
 * runtime without downloading anything else.
 */
import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { format, resolveConfig } from 'prettier';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { convertPythonProtocol } from '../src/protocol/convert.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'src', 'protocol', 'data');
const TREE = 'https://api.github.com/repos/Blizzard/heroprotocol/git/trees/master?recursive=1';
const RAW = 'https://raw.githubusercontent.com/Blizzard/heroprotocol/master/heroprotocol/versions';

const fromArg = process.argv.indexOf('--from');
const fromDir = fromArg >= 0 ? process.argv[fromArg + 1] : undefined;

/** git blob SHA-1 of file content, identical to what the GitHub tree reports. */
function blobSha(content: Uint8Array): string {
  return createHash('sha1').update(`blob ${content.byteLength}\0`).update(content).digest('hex');
}

interface Entry { build: number; sha: string; source?: string }
const entries: Entry[] = [];

if (fromDir) {
  for (const name of await readdir(fromDir)) {
    const m = /^protocol(\d+)\.py$/.exec(name);
    if (!m) continue;
    const bytes = await readFile(join(fromDir, name));
    entries.push({ build: Number(m[1]), sha: blobSha(bytes), source: bytes.toString('utf8') });
  }
} else {
  const res = await fetch(TREE, { headers: { accept: 'application/vnd.github+json' } });
  if (!res.ok) throw new Error(`GitHub tree: HTTP ${res.status}`);
  const tree = (await res.json()) as { tree: { path: string; sha: string }[] };
  for (const t of tree.tree) {
    const m = /^heroprotocol\/versions\/protocol(\d+)\.py$/.exec(t.path);
    if (m) entries.push({ build: Number(m[1]), sha: t.sha });
  }
}
entries.sort((a, b) => a.build - b.build);

// representative = lowest build per sha
const representativeBySha = new Map<string, number>();
for (const e of entries) if (!representativeBySha.has(e.sha)) representativeBySha.set(e.sha, e.build);

/** Write a generated source file formatted with the workspace prettier config, so a
 *  regeneration is byte-identical to what `pnpm fix` leaves in the tree. */
async function writeSource(path: string, content: string): Promise<void> {
  const options = (await resolveConfig(path)) ?? {};
  await writeFile(path, await format(content, { ...options, filepath: path }));
}

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

const representatives: { build: number; sha: string }[] = [];
for (const [sha, build] of representativeBySha) {
  const entry = entries.find((e) => e.build === build)!;
  const source = entry.source ?? (await (await fetch(`${RAW}/protocol${build}.py`)).text());
  const def = convertPythonProtocol(source, build);
  const body = JSON.stringify(def, null, 1);
  await writeSource(
    join(OUT, `protocol-${build}.ts`),
    `// Generated by tools/generate-protocols.mts from Blizzard/heroprotocol (protocol${build}.py, blob ${sha}). Do not edit.\n` +
      `import type { ProtocolDefinition } from '../definition.js';\n\n` +
      `const protocol: ProtocolDefinition = ${body};\n\nexport default protocol;\n`,
  );
  representatives.push({ build, sha });
}
representatives.sort((a, b) => a.build - b.build);

const index: Record<string, number> = {};
for (const e of entries) index[String(e.build)] = representativeBySha.get(e.sha)!;

await writeSource(
  join(OUT, 'index.ts'),
  `// Generated by tools/generate-protocols.mts. Do not edit.\n` +
    `import type { BuildIndex, ProtocolDefinition } from '../definition.js';\n\n` +
    `/** Every published build -> the representative build whose definition it shares. */\n` +
    `export const BUILD_INDEX: BuildIndex = ${JSON.stringify(index)};\n\n` +
    `/** Representative builds, ascending, with the git blob SHA of their Python source. */\n` +
    `export const REPRESENTATIVES: ReadonlyArray<{ readonly build: number; readonly sha: string }> = ${JSON.stringify(representatives)};\n\n` +
    `/** Lazy loaders, so a consumer bundles only the definitions a replay actually needs. */\n` +
    `export const BUNDLED: Readonly<Record<number, () => Promise<ProtocolDefinition>>> = {\n` +
    representatives.map((r) => `  ${r.build}: () => import('./protocol-${r.build}.js').then((m) => m.default),`).join('\n') +
    `\n};\n`,
);

console.log(`${entries.length} builds -> ${representatives.length} protocols written to ${OUT}`);
